pipeline {
  agent any
  options {
    timestamps()
    ansiColor('xterm')
    timeout(time: 20, unit: 'MINUTES')
  }
  environment {
    REGISTRY = 'localhost:5050'
    IMAGE_NAME = 'api-gateway'
    DOCKER_BUILDKIT = '1'
  }
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }
    stage('Build') {
      steps {
        dir('microservicios/api-gateway') {
          sh 'npm ci --quiet'
        }
      }
    }
    stage('Test') {
      steps {
        dir('microservicios/api-gateway') {
          sh 'npm test -- --coverage --ci'
        }
      }
      post {
        always {
          junit 'microservicios/api-gateway/reports/*.xml'
        }
      }
    }
    stage('Quality') {
      steps {
        dir('microservicios/api-gateway') {
          sh 'npm test -- --coverage --coverageThreshold=\'{"global":{"lines":70}}\''
        }
      }
    }
    stage('Package') {
      steps {
        dir('microservicios/api-gateway') {
          sh 'docker build -t ${REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER} .'
          sh 'docker tag ${REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER} ${REGISTRY}/${IMAGE_NAME}:latest'
        }
      }
    }
  }
  post {
    success { echo "Pipeline ${env.IMAGE_NAME} completado exitosamente" }
    failure { echo "Pipeline ${env.IMAGE_NAME} fallo en stage: ${env.STAGE_NAME}" }
    always { cleanWs() }
  }
}
