pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = 'localhost:5050'
        SERVICE_NAME = 'gestion-empleados'
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn compile'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Quality') {
            steps {
                sh 'mvn jacoco:check'
            }
        }
        stage('Package') {
            steps {
                sh 'docker build -t ${DOCKER_REGISTRY}/${SERVICE_NAME}:${BUILD_NUMBER} .'
                sh 'docker push ${DOCKER_REGISTRY}/${SERVICE_NAME}:${BUILD_NUMBER}'
            }
        }
    }

    post {
        always {
            junit 'target/surefire-reports/*.xml'
            jacoco publisher: [[pattern: 'target/site/jacoco/jacoco.xml']]
        }
    }
}
