pipeline {
    agent any
    options {
        timestamps()
        ansiColor('xterm')
        timeout(time: 20, unit: 'MINUTES')
    }
    environment {
        REGISTRY = 'localhost:5050'
        IMAGE_NAME = 'notificaciones'
        DOCKER_BUILDKIT = '1'
    }
    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Build') {
            steps {
                dir('microservicios/notificaciones') {
                    sh 'pip install -r requirements.txt --quiet'
                }
            }
        }
        stage('Test') {
            steps {
                dir('microservicios/notificaciones') {
                    sh 'pytest --cov=src --cov-report=xml -q'
                }
            }
            post {
                always {
                    junit 'microservicios/notificaciones/**/test-reports/*.xml'
                }
            }
        }
        stage('Quality') {
            steps {
                dir('microservicios/notificaciones') {
                    sh 'pytest --cov=src --cov-fail-under=70 -q'
                }
            }
        }
        stage('Package') {
            steps {
                dir('microservicios/notificaciones') {
                    sh 'docker build -t ${REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER} .'
                    sh 'docker tag ${REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER} ${REGISTRY}/${IMAGE_NAME}:latest'
                }
            }
        }
    }
    post {
        success { echo "Pipeline ${env.IMAGE_NAME} completado exitosamente" }
        failure { echo "Pipeline ${env.IMAGE_NAME} fallo en stage: ${env.STAGE_NAME}" }
        always { cleanWs() }
    }
}
